// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALNyF3ocJXhJFaFEYUO47HKSqeNHaovg0',
    appId: '1:394398775560:web:77f5c583ca58b4d6b014bd',
    messagingSenderId: '394398775560',
    projectId: 'attuneapp-c90fc',
    authDomain: 'attuneapp-c90fc.firebaseapp.com',
    storageBucket: 'attuneapp-c90fc.appspot.com',
    measurementId: 'G-ZKTGCCPLXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCnDDJ_K1qqMT4Ce26KkzUm-c7R3sqrs',
    appId: '1:394398775560:android:20f74e35a244ebcab014bd',
    messagingSenderId: '394398775560',
    projectId: 'attuneapp-c90fc',
    storageBucket: 'attuneapp-c90fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXx6PSBhrQpe5Rz10zaT8FaqnERWpfX-M',
    appId: '1:394398775560:ios:5ba16044edaa3377b014bd',
    messagingSenderId: '394398775560',
    projectId: 'attuneapp-c90fc',
    storageBucket: 'attuneapp-c90fc.appspot.com',
    iosBundleId: 'com.example.attuneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXx6PSBhrQpe5Rz10zaT8FaqnERWpfX-M',
    appId: '1:394398775560:ios:48924256add88ffdb014bd',
    messagingSenderId: '394398775560',
    projectId: 'attuneapp-c90fc',
    storageBucket: 'attuneapp-c90fc.appspot.com',
    iosBundleId: 'com.example.attuneApp.RunnerTests',
  );
}
